### ISSUE TITLE
Feature Request: Allow drag and drop to rearrange errand list

### ISSUE THREAD

**Issue by imran-mrp** [mrvladus/Errands#256] opened 2024-05-07 02:36 UTC
Adding a new errand list puts the new list at the bottom. It would be nice if we can rearrange the errand list using drag and drop. Thanks!

**Comment by mrvladus** [comment] 2024-05-07 07:29
Duplicate of #177. It's in planned features.

**Closed by mrvladus** 2024-05-07 07:29 UTC
