### ISSUE TITLE
[Feature request] Add support for repeating tasks & reminders 

### ISSUE THREAD

**Issue by ColbyB722** [mrvladus/Errands#241] opened 2024-04-26 09:19 UTC
This app is very very good already. Only thing keeping me from using it as much as I would like to is that there is currently no reocurring task option that can be set to repeat every day, 2 days,  week, 2 weeks, 3 weeks, 12th of every month, 5 months,  etc...

**Comment by mrvladus** [comment] 2024-04-26 09:22
I'm working on that :) After next release in couple of days, that will be the feature I will focus on.

**Comment by mrvladus** [comment] 2024-04-30 14:06
Closing as duplicate of #90

**Closed by mrvladus** 2024-04-30 14:06 UTC
