### ISSUE TITLE
Help Help!  I added one new todo item and now all my todos are GONE?

### ISSUE THREAD

**Issue by kobaz** [mrvladus/Errands#186] opened 2024-01-28 18:26 UTC
I was manually copying from my old todo app (xpad) and making new todo items in Errands one by one.

All of a sudden all my TODOs are missing from all my categories are gone.

Where is the data stored for errands?  And how do I get my todos back?

Thanks.

**Comment by mrvladus** [comment] 2024-01-28 20:51
Data stored in sqlite database at ~/.var/app/io.github.mrvladus.List/data/errands/data.db

**Comment by mrvladus** [comment] 2024-01-28 20:52
How exactly you copied tasks? Just writing them or imported?

**Comment by mrvladus** [comment] 2024-01-28 20:57
Can you add more info? Like version, is it a fresh install, steps to reproduce, terminal output or log file at ~/.var/app/io.github.mrvladus.List/data/errands/log.txt

**Comment by kobaz** [comment] 2024-01-29 01:45
I was copying tasks via just copy/paste.
I had added about 75 tasks across 7 lists already.
I added a new task, hit save... and then all my tasks were deleted except for 3

I loaded up the database at ~/.var/app/io.github.mrvladus.List/data/errands/data.db
sqlite> select count(*) from lists;
7
sqlite> select count(*) from tasks;
3

Everything is gone :(
I've lost months and months and months of todo task collections.  My process of migration was, any time I added a new task to errands, I removed it from my old app.

I found the log files, but they are mostly internal debug related.  Is there any log of what text was added into the lists?

Version is 45.1.5
Sync is not enabled

[log.old.txt](https://github.com/mrvladus/Errands/files/14078744/log.old.txt)

log.txt doesn't have much of anything, but log.old.txt does (attached)

**Comment by mrvladus** [comment] 2024-01-29 07:19
I'm very sorry to hear that... That's sucks. Did you use drag n drop? Because this version has this stupid bug when dragging task in one list deleted all the other tasks in all lists. As soon as I found that, I immediately released new version with bugfix on flathub.

**Comment by mrvladus** [comment] 2024-01-29 07:21
I did not put task text in logs because of the privacy reasons, but I'll add backups from now on.

**Comment by kobaz** [comment] 2024-01-29 13:53
"Did you use drag n drop? "

This rings a bell.  I think that's what happened.  I kind of remember seeing a todo floating around.  When it released, that's when everything went away.

**Comment by mrvladus** [comment] 2024-02-06 16:03
Closing as problem was fixed in recent releases

**Closed by mrvladus** 2024-02-06 16:03 UTC
